<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="3" ignored="0" total="6" passed="3">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="8697" started-at="2020-05-20T11:38:38 IST" finished-at="2020-05-20T11:38:47 IST">
    <groups>
    </groups>
    <test name="Default test" duration-ms="8697" started-at="2020-05-20T11:38:38 IST" finished-at="2020-05-20T11:38:47 IST">
      <class name="com.EmployeeApi.TestCases.TC002_Get_Single_Employee_Data">
        <test-method status="PASS" signature="Setup()[pri:0, instance:com.EmployeeApi.TestCases.TC002_Get_Single_Employee_Data@27a5f880]" name="Setup" is-config="true" duration-ms="74" started-at="2020-05-20T11:38:38 IST" finished-at="2020-05-20T11:38:38 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Setup -->
        <test-method status="PASS" signature="getAllEmployeesDetails()[pri:0, instance:com.EmployeeApi.TestCases.TC002_Get_Single_Employee_Data@27a5f880]" name="getAllEmployeesDetails" is-config="true" duration-ms="8500" started-at="2020-05-20T11:38:38 IST" finished-at="2020-05-20T11:38:46 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- getAllEmployeesDetails -->
        <test-method status="PASS" signature="checkContentType()[pri:0, instance:com.EmployeeApi.TestCases.TC002_Get_Single_Employee_Data@27a5f880]" name="checkContentType" duration-ms="10" started-at="2020-05-20T11:38:46 IST" finished-at="2020-05-20T11:38:46 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- checkContentType -->
        <test-method status="FAIL" signature="checkResponseBody()[pri:0, instance:com.EmployeeApi.TestCases.TC002_Get_Single_Employee_Data@27a5f880]" name="checkResponseBody" duration-ms="31" started-at="2020-05-20T11:38:46 IST" finished-at="2020-05-20T11:38:46 IST">
          <exception class="java.lang.AssertionError">
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: 
at org.testng.AssertJUnit.fail(AssertJUnit.java:47)
at org.testng.AssertJUnit.assertTrue(AssertJUnit.java:20)
at org.testng.AssertJUnit.assertTrue(AssertJUnit.java:26)
at com.EmployeeApi.TestCases.TC002_Get_Single_Employee_Data.checkResponseBody(TC002_Get_Single_Employee_Data.java:47)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:134)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:597)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:816)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(ArrayList.java:1257)
at org.testng.TestRunner.privateRun(TestRunner.java:766)
at org.testng.TestRunner.run(TestRunner.java:587)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1187)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1109)
at org.testng.TestNG.runSuites(TestNG.java:1039)
at org.testng.TestNG.run(TestNG.java:1007)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- checkResponseBody -->
        <test-method status="PASS" signature="checkResponseTime()[pri:0, instance:com.EmployeeApi.TestCases.TC002_Get_Single_Employee_Data@27a5f880]" name="checkResponseTime" duration-ms="4" started-at="2020-05-20T11:38:46 IST" finished-at="2020-05-20T11:38:46 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- checkResponseTime -->
        <test-method status="PASS" signature="checkServerType()[pri:0, instance:com.EmployeeApi.TestCases.TC002_Get_Single_Employee_Data@27a5f880]" name="checkServerType" duration-ms="3" started-at="2020-05-20T11:38:46 IST" finished-at="2020-05-20T11:38:46 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- checkServerType -->
        <test-method status="FAIL" signature="checkStatusLine()[pri:0, instance:com.EmployeeApi.TestCases.TC002_Get_Single_Employee_Data@27a5f880]" name="checkStatusLine" duration-ms="4" started-at="2020-05-20T11:38:46 IST" finished-at="2020-05-20T11:38:47 IST">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected:<HTTP/1.1 200 OK> but was:<HTTP/1.1 400 Bad Request>]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected:<HTTP/1.1 200 OK> but was:<HTTP/1.1 400 Bad Request>
at org.testng.AssertJUnit.assertEquals(AssertJUnit.java:82)
at org.testng.AssertJUnit.assertEquals(AssertJUnit.java:87)
at com.EmployeeApi.TestCases.TC002_Get_Single_Employee_Data.checkStatusLine(TC002_Get_Single_Employee_Data.java:76)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:134)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:597)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:816)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(ArrayList.java:1257)
at org.testng.TestRunner.privateRun(TestRunner.java:766)
at org.testng.TestRunner.run(TestRunner.java:587)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1187)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1109)
at org.testng.TestNG.runSuites(TestNG.java:1039)
at org.testng.TestNG.run(TestNG.java:1007)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- checkStatusLine -->
        <test-method status="FAIL" signature="checkStatuscode()[pri:0, instance:com.EmployeeApi.TestCases.TC002_Get_Single_Employee_Data@27a5f880]" name="checkStatuscode" duration-ms="3" started-at="2020-05-20T11:38:47 IST" finished-at="2020-05-20T11:38:47 IST">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected:<400> but was:<200>]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected:<400> but was:<200>
at org.testng.AssertJUnit.fail(AssertJUnit.java:47)
at org.testng.AssertJUnit.failNotEquals(AssertJUnit.java:330)
at org.testng.AssertJUnit.assertEquals(AssertJUnit.java:66)
at org.testng.AssertJUnit.assertEquals(AssertJUnit.java:213)
at org.testng.AssertJUnit.assertEquals(AssertJUnit.java:218)
at com.EmployeeApi.TestCases.TC002_Get_Single_Employee_Data.checkStatuscode(TC002_Get_Single_Employee_Data.java:55)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:134)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:597)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:816)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(ArrayList.java:1257)
at org.testng.TestRunner.privateRun(TestRunner.java:766)
at org.testng.TestRunner.run(TestRunner.java:587)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1187)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1109)
at org.testng.TestNG.runSuites(TestNG.java:1039)
at org.testng.TestNG.run(TestNG.java:1007)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- checkStatuscode -->
        <test-method status="PASS" signature="TearDown()[pri:0, instance:com.EmployeeApi.TestCases.TC002_Get_Single_Employee_Data@27a5f880]" name="TearDown" is-config="true" duration-ms="1" started-at="2020-05-20T11:38:47 IST" finished-at="2020-05-20T11:38:47 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TearDown -->
      </class> <!-- com.EmployeeApi.TestCases.TC002_Get_Single_Employee_Data -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
